### ISSUE TITLE
How can I use $ref to reference to another file in my express project?

### ISSUE THREAD

**Issue by FieryCod** [apigee-127/swagger-tools#492] opened 2017-04-02 09:18 UTC
I've read some of discussions how to point with $ref to another file, as I know the only possibility for now is to use json-refs. The problem is that I do not know how to make it work in my current 
[project.](https://github.com/FieryCod/KNIT-homepage-back/tree/tstojs_migration)

I'm receiving following error:
```
 #/paths/~1persons/get/parameters/0/$ref: Reference could not be resolved
~ │: ./api/swagger/parameters.yaml#parameters/Limit
```
I would highly appreciate your help in making this thing work.

**Comment by k911** [comment] 2017-04-02 11:09
We've managed to work around this problem by using absoute paths: [see swagger.yaml](https://github.com/FieryCod/KNIT-homepage-back/blob/tstojs_migration/api/swagger/swagger.yaml)
But without doubt realative paths would be much welcome here.

**Comment by whitlockjc** [comment] 2017-04-02 16:27
This is a duplicate of #227.

**Closed by whitlockjc** 2017-04-02 16:27 UTC
