### ISSUE TITLE
Validation fails when spec has same named query params of different paramTypes

### ISSUE THREAD

**Issue by nikhiljindal** [apigee-127/swagger-tools#307] opened 2015-11-30 23:14 UTC
Kubernetes has an operation that has a query param and a path param, both named "path": https://github.com/kubernetes/kubernetes/blob/master/api/swagger-spec/v1.json#L6670.

Running swagger-tools validates complains saying:

```
$ swagger-tools validate api/swagger-spec/resourceListing.json api/swagger-spec/api.json api/swagger-spec/v1.json api/swagger-spec/version.json api/swagger-spec/apis.json api/swagger-spec/extensions.json api/swagger-spec/v1beta1.json

  API Declaration (/api/v1) Errors:

    #/apis/60/operations/0/parameters/3/name: Parameter already defined: path
    #/apis/60/operations/1/parameters/3/name: Parameter already defined: path
    #/apis/60/operations/2/parameters/3/name: Parameter already defined: path
    #/apis/60/operations/3/parameters/3/name: Parameter already defined: path
    #/apis/60/operations/4/parameters/3/name: Parameter already defined: path
    #/apis/60/operations/5/parameters/3/name: Parameter already defined: path

6 errors and 0 warnings
```

Is it intended?
It should be fine for 2 params of different param types to have the same name?

fwiw, discussion on same issue with swagger-codegen where this problem was fixed: https://github.com/swagger-api/swagger-codegen/issues/1422

**Comment by whitlockjc** [comment] 2015-11-30 23:17
Duplicate of #184.

**Closed by whitlockjc** 2015-11-30 23:17 UTC
