### ISSUE TITLE
Nested query parameters not parsed

### ISSUE THREAD

**Issue by andyjbas** [apigee-127/swagger-tools#294] opened 2015-10-29 08:19 UTC
```YAML
# swagger spec
parameters:
  - name: page[limit]
    in: query
    required: false
    type: integer
    format: int32
    default: 10
  - name: page[offset]
    in: query
    required: false
    type: integer
    format: int32
    default: 0
```

It looks like `body-parser` will parse those into something like `{page: {limit: '10', offset: '0'}}` and so [when the value for the param is looked up in swagger tools](https://github.com/apigee-127/swagger-tools/blob/master/middleware/helpers.js#L104) via `req.query[parameter.name]`, it returns nothing. 

I can't find anything in the swagger spec about not supporting this. I am specifically following the [jsonapi specification](http://jsonapi.org/format/#fetching-pagination), which is where my use case comes from.

**Comment by whitlockjc** [comment] 2015-10-29 14:57
I'm not sure that's a valid Swagger parameter name.  @webron?

**Comment by webron** [comment] 2015-10-29 15:57
As far as I can tell, that's a valid parameter name for a query parameter. The spec doesn't go into the details on whether those names need to be encoded, but I'd say for the sake of readability it's safe to assume those are not encoded and should be encoded upon execution by the various tools.

**Comment by whitlockjc** [comment] 2015-10-29 16:38
What I'm asking is does Swagger provide a mechanism similar to what is being requested?  We're parsing the parameters just fine, no runtime error, but the name `page[limit]` is definitely not expected.  I'll fix it if Swagger supports having nested query parameters like this but if it doesn't, I see no reason to support it.

**Comment by whitlockjc** [comment] 2015-10-29 16:40
Basically, the argument that body-parser supports it is not enough to mean Swagger supports it.  Express support optional path parameters and other cool things but since Swagger doesn't, we do not either.  Once @webron tells me that nested parameters are supported by Swagger and that your approach falls within Swagger's support, I'll gladly support this.

**Comment by webron** [comment] 2015-10-29 16:44
Okay, I have no idea what body-parser is or what it does, and not sure I follow what you mean by nested parameters.

If you expect that having things like `page[limit]`, `page[offset]` translate into a single object `page` with two properties, that has nothing to do with Swagger and is left for interpretation of the parsing tool. As far as Swagger is concerned, there are two parameters with those exact name, no relationship whatsoever.

If the issue is different than that, please provide more information to help me understand.

**Comment by whitlockjc** [comment] 2015-10-29 17:02
If Swagger doesn't care, I guess I have no choice but to support this.  To me it seems like the parameter name is being abused but who am I to tell someone they can't do it?

**Comment by whitlockjc** [comment] 2015-10-29 17:34
For those following at home, it's not body-parser that supports this but [qs](https://github.com/hapijs/qs#parsing-objects).

**Comment by whitlockjc** [comment] 2015-10-29 17:41
Supporting this would be trivial so my concern is not with an effort thing but a *"should we allow this"* type thing.  The purpose of Swagger's `name` field is to provide a parameter name.  But what is being proposed is not a name but a pattern.  To consume this pattern, you have to understand what it means and how to process it.  Knowing that swagger-tools' middleware uses qs means I know how to process this but for others, like API consumers or swagger-ui or what not, they don't know or care.  So while supporting this isn't a problem, it promotes Swagger documents that are not portable because the brackets in the parameter name are backend specific and not necessarily a documented/supported Swagger pattern.

From an implementation perspective, how do I know that the user didn't intend to have a parameter with a name of `page[limit]` instead of a pattern?  Once I **know** the intent was a pattern instead of a name, the work is pretty simple.

I need to think a little more.

**Comment by whitlockjc** [comment] 2015-10-29 18:14
I guess we'll support it.  We need to also update how we're handling arrays as well.

**Comment by whitlockjc** [comment] 2015-10-29 18:34
The plan will be to support this.  Since the purpose of the Swagger document is to describe the outward contract, using `page[limit]` and `page[offset]` are valid and we need to support it.

**Comment by andyjbas** [comment] 2015-10-30 05:31
Thanks!

**Comment by whitlockjc** [comment] 2015-10-30 15:32
No problem and thanks for letting me about think this aloud.

**Comment by whitlockjc** [comment] 2016-01-08 17:39
Supporting this was surprisingly easy thanks to `_.get` from lodash.  :)  This will be in the next release, sorry for the delay.

**Closed** 2016-01-08 17:39 UTC

**Comment by whitlockjc** [comment] 2016-01-14 16:33
`swagger-tools@0.9.11` is release with this change.

**Comment by andyjbas** [comment] 2016-01-16 18:06
Awesome, thanks!
