### ISSUE TITLE
Route parameters defined outside of HTTP verbs are not supported

### ISSUE THREAD

**Issue by epoberezkin** [apigee-127/swagger-tools#309] opened 2015-12-08 17:45 UTC

**Comment by whitlockjc** [comment] 2015-12-08 19:32
I'll need more information for this.  It seems the issue is that swagger-ui doesn't support path parameters defined outside of an operation but I can't tell what the issue is.  We have tests in swagger-tools for handling globally defined and path-level defined parameters so I'm not sure what isn't working.

**Comment by epoberezkin** [comment] 2015-12-08 19:41
Yes, this is exactly the case.

Parameters outside of the operations are ignored by swagger-ui (or swagger-ui middleware)

```
  /nav/{nav}/{geo}:
    x-swagger-router-controller: navigation

    parameters:
      - name: nav
        description: Navigation type
        in: path
        required: true
        type: integer
        enum: [1, 2]
      - name: geo
        description: Geo tag (e.g. GB)
        in: path
        required: true
        type: string
        pattern: "[A-Z]{2}"

    get:
      description: Get navigation zone
      operationId: getNavigation
      tags:
        - navigation
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/nav_zone"
        default:
          description: Error
          schema:
            $ref: "#/definitions/error_response"

    post:
      description: Create top level nav item
      operationId: createNavItem
      tags:
        - navigation
      parameters:
        - name: body
          in: body
          required: false
          schema:
            type: object
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/nav_zone"
        default:
          description: Error
          schema:
            $ref: "#/definitions/error_response"
```

**Comment by whitlockjc** [comment] 2015-12-08 19:54
If the issue is with swagger-ui, it should be reported there.  I've searched their issues list and there are a number of issues that could be related to this one.  I'm going to close this for now but feel free to reopen if you think the issue is with swagger-tools.

**Comment by epoberezkin** [comment] 2015-12-08 19:55
Thanks

**Closed by whitlockjc** 2015-12-08 19:54 UTC
