### ISSUE TITLE
Upgrade swagger-ui  - Mixed content issues due to XHR over HTTP made from HTTPS page

### ISSUE THREAD

**Issue by jp** [apigee-127/swagger-tools#484] opened 2017-03-13 17:59 UTC
Hello,

It is not currently possible to use swagger-tools over an HTTPS API.
It was a bug in swagger-ui that was apparently fixed few weeks ago: https://github.com/swagger-api/swagger-ui/issues/1670
Swagger-ui should be updated to a more recent version.

Cheers.

**Comment by whitlockjc** [comment] 2017-03-17 15:26
Duplicate of #384.

**Closed by whitlockjc** 2017-03-17 15:26 UTC
