### ISSUE TITLE
validation errors are swallowed

### ISSUE THREAD

**Issue by seanpk** [apigee-127/swagger-tools#355] opened 2016-02-23 22:23 UTC
if I call `initializeMiddelware` with a bad spec, I just get an ugly traceback, e.g.:

```
Error: Swagger document(s) failed validation so the server cannot start
    at /tmp/my-project/node_modules/swagger-tools/index.js:74:13
    at /tmp/my-project/node_modules/swagger-tools/lib/specs.js:1231:7
    at /tmp/my-project/node_modules/swagger-tools/lib/specs.js:1073:29
    at validateAgainstSchema (/tmp/my-project/node_modules/swagger-tools/lib/specs.js:712:14)
    at validateStructurally (/tmp/my-project/node_modules/swagger-tools/lib/specs.js:1045:3)
    at Specification.validate (/tmp/my-project/node_modules/swagger-tools/lib/specs.js:1229:3)
    at Object.initializeMiddleware (/tmp/my-project/node_modules/swagger-tools/index.js:133:17)
    at /tmp/my-project/middleware/api-specs.js:47:22
    at /tmp/my-project/node_modules/lodash/index.js:3073:15
    at baseForOwn (/tmp/my-project/node_modules/lodash/index.js:2046:14)
    at /tmp/my-project/node_modules/lodash/index.js:3043:18
    at Function.<anonymous> (/tmp/my-project/node_modules/lodash/index.js:3346:13)
    at init (/tmp/my-project/middleware/api-specs.js:44:7)
    at initConsumer (/tmp/my-project/node_modules/blueoak-server/lib/loader.js:262:37)
    at /tmp/my-project/node_modules/blueoak-server/node_modules/async/lib/async.js:181:20
    at iterate (/tmp/my-project/node_modules/blueoak-server/node_modules/async/lib/async.js:262:13)
```

But, if I add `err.failedValidation = true;` to the error condition in `index.js` (I can create a pull request if necessary, but I'll comment with the code snippet), I get some useful output:
```
API Errors:

  #/responses/NotFound: Missing required property: description
  #/responses/NotFound: Additional properties not allowed: $ref
  #/responses/InvalidRequestData: Missing required property: description
  #/responses/InvalidRequestData: Additional properties not allowed: $ref
  #/responses/InvalidApiKey: Missing required property: description
  #/responses/InvalidApiKey: Additional properties not allowed: $ref
  #/responses/CreatedClaim: Missing required property: description
  #/responses/CreatedClaim: Additional properties not allowed: $ref
  #/parameters/QueryInsuredName: Not a valid parameter definition
    #/parameters/QueryInsuredName: Missing required property: schema
    #/parameters/QueryInsuredName: Missing required property: type
  #/parameters/QueryDate: Not a valid parameter definition
    #/parameters/QueryDate: Missing required property: schema
    #/parameters/QueryDate: Missing required property: type
  #/parameters/QueryById: Not a valid parameter definition
    #/parameters/QueryById: Missing required property: schema
    #/parameters/QueryById: Missing required property: type
  #/parameters/QueryAddress: Not a valid parameter definition
    #/parameters/QueryAddress: Missing required property: schema
    #/parameters/QueryAddress: Missing required property: type
  #/parameters/PathId: Not a valid parameter definition
    #/parameters/PathId: Missing required property: schema
    #/parameters/PathId: Missing required property: type

13 errors and 0 warnings
```

I assume the nice output is the desired behavior ... will you publish a fix?

**Comment by seanpk** [comment] 2016-02-23 22:26
**fix in index.js**

```js
//...
  args.push(function (err, results) {
    if (results && results.errors.length + _.reduce(results.apiDeclarations || [], function (count, apiDeclaration) {
      return count += (apiDeclaration ? apiDeclaration.errors.length : 0);
    }, 0) > 0) {
      err = new Error('Swagger document(s) failed validation so the server cannot start');
      err.failedValidation = true; // <--- this is the addition
      err.results = results;
    }

    debug('  Validation: %s', err ? 'failed' : 'succeeded');
//...
```

**Comment by whitlockjc** [comment] 2016-02-24 00:38
I think this is a duplicate of #327.  If you agree, do you mind closing this?

**Comment by seanpk** [comment] 2016-02-24 03:49
@whitlockjc - thanks for the quick reply!
 
I had looked at #327 before, but I think there _is_ a difference:
While it would be great to recover from a validation error programmatically (#327), it is OK for my case to ask the swagger developers to manually recover from the error by fixing their spec and restarting the server (the validation failure happens at server startup anyway).
All that I'm looking for is the validation errors to be printed to the console instead of the obtuse traceback.

As far as I can tell (and definitely for my case), adding the one line referenced in my previous comment does the trick.
i.e.:
```js
err.failedValidation = true;
```

**Comment by whitlockjc** [comment] 2016-02-24 16:40
Let's keep it open then.  I realize that `err.failedValidation` dictates some things and maybe I neglected to set it in some place.

**Comment by seanpk** [comment] 2016-02-24 17:12
ok, yeah ... in this case, a new `Error` is created with the message _Swagger document(s) failed validation so the server cannot start_, so `.failedValidation` needs to be added to that error before control continues to the rest of the code

**Comment by whitlockjc** [comment] 2016-02-24 17:21
Do you want to create a PR?  I could help you out if need be.  If not, I can whip this up pretty quickly.

**Comment by whitlockjc** [comment] 2016-02-24 21:41
`swagger-tools@0.10.1` is out with this fix in it.  Thanks for your help.

**Closed by whitlockjc** 2016-02-24 21:41 UTC

**Comment by seanpk** [comment] 2016-02-25 00:57
awesome - thanks for yours
