### ISSUE TITLE
x-swagger-router-validater for the validation

### ISSUE THREAD

**Issue by fastcodejava** [apigee-127/swagger-tools#424] opened 2016-09-11 17:39 UTC
Can we add x-swagger-router-validater (similar to x-swagger-router-controller) for validation? 
Right now we are having to do all the validation in the cod​e​.
It would be nice if ​s​wagger ​tools ​itself can do it.

**Comment by whitlockjc** [comment] 2016-09-12 15:19
I'm not sure I understand.  If you use the `swagger-validator` middleware, you get validation already.  That's one of the main features of swagger-tools.

**Comment by fastcodejava** [comment] 2016-09-12 16:02
Sorry this is for more custom validation on top of the built in validation. 
Here is more detailed [description ](https://github.com/apigee-127/swagger-tools/issues/423).

**Comment by whitlockjc** [comment] 2016-09-12 16:08
This is a duplicate of #140.

**Closed by whitlockjc** 2016-09-12 16:08 UTC
