### ISSUE TITLE
Add support to "find" API Declarations based on the location of the Resource Listing

### ISSUE THREAD

**Issue by earth2marsh** [apigee-127/swagger-tools#168] opened 2015-02-26 02:16 UTC
I wanted to validate a 1.2 spec that has 195 resource-children declarations. Especially with a remote spec, it would be AWESOME if I could pass in ONLY the root declaration and the validator would crawl the child declarations by using the `apis` listed in the api-docs root.

**Comment by whitlockjc** [comment] 2015-04-17 19:26
This is a duplicate of #164.

**Closed by whitlockjc** 2015-04-17 19:26 UTC
Labels: enhancement, Swagger 1.2
