### ISSUE TITLE
When swaggerUi middleware is invoked from inside an express router/subapp, the default path to the api-docs is incorrect

### ISSUE THREAD

**Issue by keithchilders** [apigee-127/swagger-tools#250] opened 2015-07-21 22:24 UTC
Consider this example:

    var express = require('express'),
          swaggerTools = require('swagger-tools'),
          app = express(),
          router = express.Router();

    swaggerTools.initializeMiddleware(someDoc, function(middleware){
        router.use(middleware.swaggerUi());
    });

    app.use('/foo/bar', router);
    app.listen(3000);

In this case, the app correctly registers the middleware at /foo/bar/api-docs and /foo/bar/docs, relative to the path the router is bound to rather than absolute to the app. But then when I go to load up swagger-ui, the default location of the api-docs in the url entry field is incorrectly set to http://localhost:3000/api-docs instead of /foo/bar/api-docs. It looks like the options.apiDocs value is being passed literally into the embedded swaggerUi instance rather than having the req.url value prepended to it first:

![image](https://cloud.githubusercontent.com/assets/7001667/8813967/6d9c3b38-2fbc-11e5-91d4-f4e08c009f8d.png)

I have tried changing options.apiDocs to tell it the correct fully qualified path to the docs, but that results in the apiDocs static middleware itself binding to the wrong path, i.e. /foo/bar/foo/bar/api-docs. As a workaround I'm just binding this middleware to the app instead of the router/subapp and using fully qualified option values to have it configure itself properly, but it would be nice to have it derive the correct path to the apiDocs from the relative path at which it is invoked.

**Comment by keithchilders** [comment] 2015-07-22 04:32
Make that "without having the req.originalUrl value appended to it first"

**Comment by whitlockjc** [comment] 2015-07-22 17:58
What if you put your `app.use` and `app.listen` in the `swaggerTools.initializeMiddleware` callback after you wire in swagger-ui?  My thought is that you're running into an order issue caused by your `app.use('/foo/bar', router);` and `app.listen(3000);` are running before the `router.use(middleware.swaggerUi());`.

**Comment by whitlockjc** [comment] 2015-07-24 20:24
Any update on this?

**Comment by keithchilders** [comment] 2015-07-27 19:01
Sorry for the delay in responding. That's what I have done as a workaround. To be clear, the middleware itself is working exactly as I would expect; only the path that the embedded swagger-ui runtime is being passed to load the api-docs from is incorrect in that it does not match the path the api-docs middleware is registering with the app.

Moving app.listen inside the initializeMiddleware() callback doesn't fix the issue.

**Comment by whitlockjc** [comment] 2015-07-27 19:13
Well that definitely doesn't sound like the original issue reported.  Can you see in the browser console what URL is attempting to be accessed?  When you take the URL from the textbox and paste it into a browser window, what do you get?

**Comment by keithchilders** [comment] 2015-07-28 19:47
So maybe the description wasn't clear, but it is the issue I intended to report. You can take express router out of the equation too, this happens with just the top level app trying to register the swaggerUi middleware at a path other than the root of the server instance.

app.use('/foo/bar', middleware.swaggerUi());

results in:

/foo/bar/api-docs - the swagger docs load
/foo/bar/docs - the swagger ui interface loads, but the default path to the api-docs in the text field at the top of the page is /api-docs not /foo/bar/api-docs as expected

Changing the value from /api-docs to /foo/bar/api-docs everything works. This issue is only about the path being passed from the middleware into the swagger-ui instance for initially loading the api-docs, not about the middleware itself not registering at the correct path.

![image](https://cloud.githubusercontent.com/assets/7001667/8941805/bf1e2880-3526-11e5-9e2d-9ac2a94d2d16.png)

**Comment by keithchilders** [comment] 2015-07-28 19:58
Also pay no attention to that 500 error in the screenshot, that was me using the metadata middleware and trying to console.out the swaggerObject at the wrong path. All the screenshot is meant to illustrate is the path in the swagger-ui text box not matching the path in the browser address bar by default.

**Comment by whitlockjc** [comment] 2015-07-28 23:42
I know a workaround but I'm not sure of the fix just yet.  swagger-ui middleware assumes it is run via `app.use(middleware)` instead of `app.use(prefix, middleware)`.  So since you didn't pass in `options.apiDocs=/foo/bar/api-docs` to the middleware, it's using the default of `/api-docs`.  I either need to document this or update the middleware to work with route mount points.

**Comment by keithchilders** [comment] 2015-07-29 04:52
It would be good if the middleware could be made to prepend req.originalUrl to the api-docs path string passed into swagger-ui. I have already worked around the issue in the manner you described, mounting the middleware at the root path and configuring the path to docs and api-docs in the options. The reason I think it would be nice to have the middleware be mount point aware is in case I want to deploy multiple versions of an API (each one having its own swagger spec and swagger-tools middleware) as routers or subapplications of a master express app. I can do that now by mounting multiple instances of the middleware to the root app, but it would probably be a more express-friendly pattern to just register the entire middleware chain or router/app at a different mount point and have it all resolve everything relative to the mount point.

**Comment by whitlockjc** [comment] 2015-08-03 16:59
I'm closing this for #256 which better identifies the problem causing this.  I'll cc you there.

**Closed** 2015-08-03 17:20 UTC

**Comment by keithchilders** [comment] 2015-08-05 21:59
Thanks!
