### ISSUE TITLE
Supertest seems to not working with swagger-tools.

### ISSUE THREAD

**Issue by FieryCod** [apigee-127/swagger-tools#495] opened 2017-04-09 16:44 UTC
The problem is that all assertions fail. I tried to use `request` module and it seems to work just fine, but `supertest` does not working at all. This is why I'm suspecting that it is because of swagger-tools.

```
/* eslint-disable func-names, prefer-arrow-callback */
/* eslint-disable no-unused-expressions */
const chai = require('chai');
const ZSchema = require('z-schema');
const request = require('supertest');
const app = require('../../app.js');
const validator = new ZSchema({ assumeAdditional: false });
const expect = chai.expect;

const articleSchema = {
  type: 'object',
  required: ['id', 'createdAt', 'author', 'content', 'title'],
  properties: {
    id: {
      type: 'integer',
    },
    content: {
      type: 'string',
    },
    title: {
      type: 'string',
    },
    author: {
      type: 'string',
    },
    createdAt: {
      type: 'string',
      format: 'date-time',
    },
  },
};

describe('article test', function () {
  it('should return 200 and a proper article', function (done){
      request(app)
        .get('/api/articles/1')
        .set('Accept', 'application/json')
        .expect('Content-Type', /json/)
        .expect(200)
        .end(function(err, res) {
          expect(err).to.be.a('null');
          expect(res.statusCode).to.equal(200);
          done();
      });
  });
});

describe('/api/swagger/swagger.yaml', function () {
  it('should return swagger.yaml file', function (done){
    request(app)
      .get('/api/swagger/swagger.yaml')
      .end(function(err, res) {
        expect(err).to.be.a('null');
        expect(res.statusCode).to.equal(200);
        done();
    });
  });
});
```

My previous test using request:
```
describe('/api/articles', function () {
  describe(' api/articles/{id}', function () {
    it('should respond with 200 Success and return article', function (done) {
      request({ uri: 'http://localhost:3000/api/articles/1', json: true })
      .then((res) => {
        expect(res).to.be.a('object');
        validator.validate(res, articleSchema);
        const errors = validator.getLastErrors();
        expect(errors).to.be.a('undefined');
        done();
      })
      .catch(err => done(err));
    });
  });
});
```
Second works, but `supertest` seems to be a better option. I would highly appreciate your help with resolving that issue.
Since I do not want that issue to be way to long, because of pasting all my code here I'm giving a link to a [repo.](https://github.com/FieryCod/KNIT-homepage-back/tree/test_integration)

**EDIT:**
My `app.js`

```

const mongoose = require('mongoose');
const express = require('express');

const config = require('./config/config.js');

const http = require('http');


mongoose.connect(`mongodb://localhost/${config.DATABASE_NAME}`);

const app = express();
config.setMiddlewares(app);

/**
 * Get port from environment and store in Express.
 */
const port = normalizePort(process.env.PORT || '3000');
app.set('port', port);

/**
 * Create HTTP server.
 */
const server = http.createServer(app);


/**
 * Listen on provided port, on all network interfaces.
 */
server.listen(port);
server.on('error', onError);
server.on('listening', onListening);

/**
 * Normalize a port into a number, string, or false.
 */
function normalizePort(val) {
  const parsedPort = parseInt(val, 10);

  // named pipe
  if (isNaN(parsedPort)) {
    return val;
  }

  // port number
  return (parsedPort >= 0) ? parsedPort : false;
}

/**
 * Event listener for HTTP server 'error' event.
 */
function onError(error) {
  if (error.syscall !== 'listen') {
    throw error;
  }

  const bind = typeof port === 'string'
    ? `Pipe ${port}`
    : `Port ${port}`;

  // handle specific listen errors with friendly messages
  switch (error.code) {
  case 'EACCES':
    console.error(`${bind} requires elevated privileges`);
    process.exit(1);
    break;
  case 'EADDRINUSE':
    console.error(`${bind} is already in use`);
    process.exit(1);
    break;
  default:
    throw error;
  }
}

/**
 * Event listener for HTTP server 'listening' event.
 */
function onListening() {
  const addr = server.address();
  const bind = typeof addr === 'string'
    ? `pipe ${addr}`
    : `port: ${addr.port}`;

  if (config.env === 'development') {
    console.info(`Localhost: Listening on ${bind}`);
  }
}

module.exports = app;
```

My `config.js`, here I am configuring `swagger-tools`.
```
const path = require('path');
const logger = require('morgan');
const bodyParser = require('body-parser');
const cookieParser = require('cookie-parser');
const helmet = require('helmet');
const swaggerTools = require('swagger-tools');
const YAML = require('js-yaml');
const JsonRefs = require('json-refs');
const errorHandlers = require('./errors.js');

const env = process.env.NODE_ENV || 'development';
const host = (env === 'development') ? 'http://localhost:3000/' : '';

const options = {
  controllers: path.join('api', 'controllers/'),
};


module.exports = {

  env,
  host,
  setMiddlewares(app) {
    app.use(helmet());
    app.use(logger('dev'));
    app.use(bodyParser.json());
    app.use(bodyParser.urlencoded({ extended: false }));
    app.use(cookieParser());
    JsonRefs.resolveRefsAt('./api/swagger/swagger.yaml', {
      // Resolve all remote references
      filter: ['relative', 'remote'],
      loaderOptions: {
        processContent(res, cb) {
          cb(undefined, YAML.safeLoad(res.text));
        },
      },
    })
    .then((results) => {
      swaggerTools.initializeMiddleware(results.resolved, (middleware) => {
        // Wire up the Swagger middleware
        // Interpret Swagger resources and attach metadata to request
        // - must be first in swagger-tools middleware chain
        app.use(middleware.swaggerMetadata());

        // Validate Swagger requests
        app.use(middleware.swaggerValidator({ validateResponse: true }));

        // Route validated requests to appropriate controller
        app.use(middleware.swaggerRouter(options));

        // Custom error handler
        app.use(errorHandlers.onSwaggerError);

        // Serve the Swagger documents and Swagger UI
        app.use(middleware.swaggerUi({
          swaggerUi: '/api/docs/',
          apiDocs: '/api/swagger/swagger.yaml',
        }));
      });
    })
    .catch((err) => {
      console.error(err.stack);
      process.exit(1);
    });
  },
  DATABASE_NAME: 'db',
};
```
I'm launching my tests using this in `package.json`.
`"test": "cross-env NODE_ENV=test ./node_modules/.bin/mocha --recursive"`

**Comment by whitlockjc** [comment] 2017-04-09 16:47
I don't see any `swagger-tools` code to even begin to diagnose this.

**Comment by FieryCod** [comment] 2017-04-09 17:29
@whitlockjc I edited my issue in order to let you see my configuration of `swagger-tools`.

**Comment by whitlockjc** [comment] 2017-04-10 05:01
Any way to see `errors.js#onSwaggerError`?  Also, I'm not sure if you know but `swagger-tools` uses `supertest` in its test suite so I'm really not thinking it's an issue with `swagger-tools` somehow working differently with `request` and `superagent`.  I wish I knew more about the failure happening but given the code, I'm not seeing anything yet.

**Comment by FieryCod** [comment] 2017-04-10 07:56
`errors.js`
```
/**
 * @param {(string|Object)} err
 * @return {{message: string, code: string}}
 */
function parseError(err) {
  if (typeof err !== 'object') {
    // Default error object
    return {
      message: String(err),
      code: 'INTERNAL_SERVER_ERROR',
    };
  } else if (typeof err.message === 'undefined' || typeof err.code === 'undefined') {
    // Error object was defined incorrectly
    return {
      message: 'Failed schema validation: this.error is not valid Error object.',
      error: err,
      failedValidation: true,
      code: 'UNKNOWN_ERROR',
    };
  }

  // Error object is valid
  return err;
}

/**
 * Resolves custom status codes
 * @param {string} code
 * @return {number}
 */
function resolveStatusCode(code) {
  switch (code) {
  case 'UNKNOWN_ERROR': // ErrorResponse is not a valid schema: swagger/models/Error.yaml#/ErrorResponse
    return 520;
  case 'NOT_IMPLEMENTED':
    return 501;
  case 'INTERNAL_SERVER_ERROR':
  default:
    return 500;
  }
}

module.exports = {
  /**
   * Custom error handler that returns them in proper format
   * defined in: swagger/models/Error.yaml#/ErrorResponse
   * @param {(Object|string)} err
   * @param {Object} req request
   * @param {Object} res response
   * @param {Function} next serves error pipe
   */
  onSwaggerError(err, req, res, next) {
    /**
     * Parse error object
     * @member {Object}
     * @property {string} message
     * @property {string} code name
     */
    const Error = parseError(err);

    // Ensure that err.message is enumerable (It is not by default)
    Object.defineProperty(Error, 'message', { enumerable: true });

    // Set headers before anything else
    res.setHeader('Content-Type', 'application/json');

    // Resolve error status code only if not done already
    if (res.statusCode < 400) { res.status(resolveStatusCode(Error.code)) }

    // Parse error to JSON
    res.end(JSON.stringify(Error));
  },
};
```
The more I'm testing my code the more I'm convinced that it is something wrong with my request. The problem is that I cannot spot an issue in my code.

**Comment by whitlockjc** [comment] 2017-04-10 16:10
Any chance your schema and the test schema you're using are different?  In your test, `articleSchema` is manually constructed and there could be a difference between it and the `articleSchema` that `swagger-tools` computed.  Just a thought.  I also am not sure what is up because the code looks fine.  What is the failure you're getting, or not getting, for the failed test?

**Comment by FieryCod** [comment] 2017-04-10 16:12
Ok I see an issue. I created two files, both looks the same. When I am launching npm test I can see that every test passes except one (2 files = 4 tests, 3 passes 1 outputs an error). But when I delete one of them
only 1 test passes ( the yaml file). If you have some time you can check what I mean by cloning my [repo].(https://github.com/FieryCod/KNIT-homepage-back/tree/test_integration)

**Comment by whitlockjc** [comment] 2017-04-10 17:15
If you're getting a `404`, `swagger-tools` isn't involved as it never throws a `404`.  The only thing that I can think of is `swagger-tools`' route handling, if you think you've wired up a route handler improperly but even that would result in a `500` and not a `404`.  You might learn more by running `swagger-tools in [debug mode](https://github.com/apigee-127/swagger-tools/blob/master/docs/Middleware.md#swagger-middleware-debugging).

**Comment by FieryCod** [comment] 2017-04-10 18:07
When I am using `npm start' I can access 'api/articles/1' only when I try tu run `npm test` I am receiving `404`. When I am disabling my error handling I am still receiving `404`. I don't think that I've wired up a route handler improperly, because when I am testing 2 same files in one of them the response is correct.

**Comment by whitlockjc** [comment] 2017-04-10 19:32
Try running your tests with debugging and see if you can notice a pattern.  I don't see anything either but I'll look when I get more time.

**Comment by FieryCod** [comment] 2017-04-17 16:04
@whitlockjc Seems that middleware is not even initialized when using mocha. ;(

**Comment by whitlockjc** [comment] 2017-04-17 16:08
Thanks for the heads up but I'm not sure that helps me help you.  :(  I'm not sure what your test runner is doing but `swagger-tools` uses `mocha` and `supertest` without issue.  I did create a simple little helper function to spin up a server just for testing, maybe that will help: https://github.com/apigee-127/swagger-tools/blob/master/test/helpers.js#L73

**Comment by FieryCod** [comment] 2017-04-17 16:40
It seems like because of using json-refs, middleware is not initialized with mocha. But when I delete json-refs everything works just fine. The problem is that I do not want to get rid of json-refs.

**Comment by whitlockjc** [comment] 2017-04-17 16:48
How are you coming to this conclusion?  `swagger-tools` itself _also_ uses `json-refs` and it seems you've got `catch` and `then` in place to handle both success and failure of `json-refs`.  The circumstances being described are not making sense because at first, this was believed to be due to `request` vs. `supertest`, and now it's something else.

You might try wrapping your `JsonRefs` stuff in a `try/catch` block _just in case_ to see if you're running into some `json-refs` bug related to circular references _(fixed but not released yet)_.  Just shooting int he dark here.

**Comment by FieryCod** [comment] 2017-04-17 17:11
I've added a console.log in the block of code where swagger-tools middleware is initialized. When I got 2 tests files it seems that middleware is initialized only once, after first test is done.

**Comment by whitlockjc** [comment] 2017-04-17 17:58
I'm not sure how you came to that conclusion but I won't disagree because I don't have enough details.  Is the repo you linked to capable of reproducing this issue?

**Comment by FieryCod** [comment] 2017-04-17 18:18
Look [here](https://github.com/FieryCod/KNIT-homepage-back/tree/test_integration) you can comment timeout and you will see that middlewares are not initialized.

**Comment by whitlockjc** [comment] 2017-04-17 19:14
Just looking at the code has me suspect that it's not `swagger-tools`.  In your tests, you're using `app.js` as if it's synchronous but it's not.  Your call to  `config.setMiddlewares()` does nothing to ensure that the middleware has initialized before continuing on with the server initialization.  What this does is it makes it where your tests can hit a live server but that is potentially missing the `swagger-tools` middleware because you have already started the server even if the `swagger-tools` middleware never initialized.

So I do believe you now that `swagger-tools` isn't fully initialized when the tests start but it's not `swagger-tools`' fault, it's your code treating asynchronous code as if its synchronous and just expecting things to work.  Let's walk through this together, starting with the test.

Your test suite sees `require('../../app.js')` and `app` is provided immediately.  To your test suite, it has all it needs to start firing tests and that's exactly what it's doing.  The problem is that in `app.js`, you call `config.setMiddlewares(app)` and the code behind that is asynchronous.  So when `app.js` continues, it continues assuming that `config.setMiddlewares(app)` has completed and starts the server and returns it via `module.exports`.  The problem is that there is no guarantee that `config.setMiddlewares(app)` has completed.  This also explains why your timeout _"fixes"_ things.

I don't see how you can ever have asynchronous code that is guaranteed to be completed and export it via `module.exports`.  On top of that, if your server requires all middleware to be initialized prior to starting the server, you need to use callbacks when calling `swaggerTools.initializeMiddleware`.  Here is a good example of this: https://github.com/apigee-127/swagger-tools/blob/master/examples/2.0/index.js#L19

**Comment by FieryCod** [comment] 2017-04-17 19:33
Ok you got right it is my fault. Is there a possibility to initialize swagger-tools synchronously, or maybe you got some idea how to make it work?

**Comment by whitlockjc** [comment] 2017-04-17 20:05
We've looked into this a lot and there really isn't a good way to do it.  I've looked into this [a few times](https://github.com/apigee-127/swagger-tools/issues?q=is%3Aissue+synchronous+is%3Aclosed) and always came to the same conclusion that if it's asynchronous, you just have to write your software accordingly.  Since resolving remote references is asynchronous, `swaggerTools.initializeMiddleware` is asynchronous because that function will attempt to resolve references even if you have none, which makes its API asynchronous.

This is about the best you can do, and even that will still be asynchronous during the `JsonRefs.resolveRefsAt` call: https://github.com/apigee-127/swagger-tools/issues/217#issuecomment-197490009

I'm closing this since it's not an issue with `swagger-tools` but we should continue discussing it until you have something working.

**Closed by whitlockjc** 2017-04-17 20:05 UTC

**Comment by whitlockjc** [comment] 2017-04-17 20:07
Also, if you want to have some real-time discussion on this, I'm on [Gitter](https://gitter.im/apigee-127/swagger-tools).

**Comment by ftwang** [comment] 2017-12-21 03:08
Hi FieryCod, have you resolved this issue?  I ran into a similar issue too, it had to do with JsonRef not resolving the file references successfully when being run using Jest, but is able to resolve correctly when being run using node.  JsonRef tried to resolve the files relative to 127.0.0.1:80 instead of the local file system.  I solved it by setting the JsonRef option.location to use the file:/// uri.  Just a thought.

```
const root = YAML.safeLoad(fs.readFileSync('./swagger/index.yaml').toString());
const yamlContentProcessor = function (res, callback) {
  callback(undefined, YAML.safeLoad(res.text));
};
const options = {
  location: `file://${process.cwd()}/swagger/index.yaml`,
  loaderOptions: {
    processContent: yamlContentProcessor,
  },
};
const swaggerDoc = await resolveRefs(root, options);
```
