### ISSUE TITLE
"Definition is defined but is not used" warning for subtypes

### ISSUE THREAD

**Issue by who** [apigee-127/swagger-tools#376] opened 2016-04-29 17:23 UTC
If you have a spec configured to use abstract parents with concrete child objects, and your APIs accept the parent type in their parameter spec, swagger-tools will throw a Warning stating that "X Definition is defined but not used".

However, this is really the whole point of using the parent-child model; you use the spec to specify that anything inheriting from the parent type is acceptable.

I propose that this warning be suppressed for subtype/child definitions.

**Comment by whitlockjc** [comment] 2016-04-29 17:26
Can you give me an example spec?

**Comment by who** [comment] 2016-04-29 19:08
Sure thing @whitlockjc : https://gist.github.com/who/a336f9a30d55e0a1a6025b855d39c2dc

The output for validating above is:

```
$ swagger-tools validate $spec

API Warnings:

  #/definitions/Dog: Definition is defined but is not used: #/definitions/Dog
  #/definitions/Cat: Definition is defined but is not used: #/definitions/Cat

Validation succeeded but with 2 warnings

```

**Comment by whitlockjc** [comment] 2016-04-29 20:57
This is a duplicate of #241.  Long story short, `discriminator` support is what is required for this to work properly.

**Closed by whitlockjc** 2016-04-29 20:57 UTC
