### ISSUE TITLE
validateContentType handles errors differently

### ISSUE THREAD

**Issue by nikdunn** [apigee-127/swagger-tools#240] opened 2015-07-06 21:43 UTC
There may be a good reason for this behaving differently. Maybe there is a work around to my issue.

I've added a custom error handler to trap errors created by swagger-tools on my server. This is working for some errors, but not others. In particular, invalid content types that are detected in "validateContentType()" in validators.js throw an Error() and are not being delivered to my custom error handler. Everywhere else seems to use the "throwErrorWithCode()" function that functions correctly.

Here is the stack that doesn't trigger the custom error handler:

Error: Response validation failed: invalid content type (text/html).  These are valid: application/vnd.osc-v1.0+json
    at Object.validateContentType (/storage/onesafSimulationCenter/server/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/lib/validators.js:188:11)
    at ServerResponse.end (/storage/onesafSimulationCenter/server/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/middleware/swagger-validator.js:168:20)
    at Array.write [as 0] (/storage/onesafSimulationCenter/server/node_modules/express/node_modules/finalhandler/index.js:126:9)
    at listener (/storage/onesafSimulationCenter/server/node_modules/express/node_modules/on-finished/index.js:164:15)
    at onFinish (/storage/onesafSimulationCenter/server/node_modules/express/node_modules/on-finished/index.js:95:5)
    at callback (/storage/onesafSimulationCenter/server/node_modules/express/node_modules/on-finished/node_modules/ee-first/index.js:33:10)
    at IncomingMessage.onevent (/storage/onesafSimulationCenter/server/node_modules/express/node_modules/on-finished/node_modules/ee-first/index.js:66:5)
    at IncomingMessage.emit (events.js:92:17)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)

An potentially interesting note is that in the express router code (index.js) the number of layers is the same, but the "idx" variable is different in the two cases. In one case, it is one less than the layers, so it calls the last handler (my custom one). In the other case, it is incremented by one and falls into the setImmediate(done, layerError) function and my handler never get called.

Thanks.

**Comment by whitlockjc** [comment] 2015-07-06 22:44
This code is working as designed but you might have run into a race condition.  It would be much easier if I could see your server *(`index.js`)* so that I can see the order in which you're registering things.  Long story short, it seems your server is falling back to the Express built-in error handler which will return a `text/html` version of your error.  Since that clearly does not match the configured `produces` for you operation, you get a response validation error.  You might want to run with `DEBUG=swagger-tools* node .` to see if you can see why the error is happening but the only error that I've found that does not go through the Connect middleware error chain are errors thrown by Express, like a 404.

This could be related but I just fixed an issue here where the server is returning a `404` for controllers not found when it should be returning a `500`: https://github.com/apigee-127/swagger-tools/commit/6650a46d186a068e27bcefeb995898a0672c38a0  The reason this matters is the `404` returned by Connect/Express does not go through the middleware error handler chain.  That being said, all errors created by swagger-tools use `next` to send all errors downstream.

Please post your `index.js`, the output of running the server with `debug` support as mentioned above and we'll go from there.  If you find this is not due to swagger-tools, please feel free to close.

**Comment by nikdunn** [comment] 2015-07-07 00:09
Okay. After some debugging and some trial and error, I was able to figure out why it was happening. I'm using the OPTIONS verb in my swagger.yaml file. That seems to blow up the GET request on the same url. When I remove that from the spec it works as expected.

I'll continue poking around at the code, but that's a clue.

**Comment by nikdunn** [comment] 2015-07-07 00:32
Actually, it looks like any HTTP verb will cause the problem, not simply OPTIONS. I added a GET and a POST at the same URL and this happens.

**Comment by nikdunn** [comment] 2015-07-07 01:00
Okay. Turns out that there was a typo in the swagger.yaml file. The function in the controller didn't match what was in the spec file. That caused a 404 not found error that got handled by the default handler as you indicated. Should it provide a better error?

It took me a while to track down the root cause. I don't understand enough of the internals to venture an opinion, but it seems that an unlinked controller shouldn't manifest as a content type error. That's two errors removed from the problem, since it seems like it goes: can't find property in controller to a 404 error that gets punted to an invalid content type error.

Should the swagger router report an error if a route specified in the spec file points to a controller that does not exist?

**Comment by whitlockjc** [comment] 2015-07-07 01:20
Ah, so that exact case was just fixed in the issue I linked against.  :)  We no fall through and allow the server to report a `404` for a missing controller.

**Comment by whitlockjc** [comment] 2015-07-07 01:21
https://github.com/apigee-127/swagger-tools/issues/155

**Comment by nikdunn** [comment] 2015-07-07 01:24
Ah perfect. I'll try it out with my test case.

**Comment by nikdunn** [comment] 2015-07-07 02:10
That worked! I had to make the error handler conform to the spec also or when I wrote out the error message you provided it would get caught up in the validator again, so it looks like it's still possible to cause misdirection in the logs. That's a little meta. Would it be a good idea to turn off validation in cases where an issue like that occurred?

**Comment by whitlockjc** [comment] 2015-07-07 03:50
Well, that depends.  :)  If you want your API to conform to your Swagger specification, response validation should happen even to server-side errors.  If your Swagger document says your API will return JSON but your error handler is returning HTML, then your API does not adhere to your Swagger document and that is itself an error.  We handle this by updating the `Error` object per the documentation here: https://github.com/apigee-127/swagger-tools/blob/master/docs/Middleware.md#validation-errors  I'm closing this since it was already solved by #155.  I'll get a release out soon.

**Closed by whitlockjc** 2015-07-07 03:50 UTC
