### ISSUE TITLE
JS error on swaggers docs page

### ISSUE THREAD

**Issue by lazar725** [apigee-127/swagger-tools#364] opened 2016-04-06 13:26 UTC
I'm using swagger tools version 0.9.15, and I'm seeing a js error when viewing the **/docs** page (print screen attached). My swagger.yaml file has been validated with a yaml validation tool and no errors were found.

Thanks for your help,
Lazar. 

<img width="943" alt="swagger-docs-error" src="https://cloud.githubusercontent.com/assets/11555813/14317590/a2578f68-fc11-11e5-99dc-90c5afb334d3.png">

**Comment by whitlockjc** [comment] 2016-04-06 15:40
This is a swagger-ui error but I will look into why it might be happening.  When you say that _"My swagger.yaml file has been validated with a yaml validation tool"_, what do you mean?  YAML validation is not the same as Swagger validation.  swagger-tools will pre-validate your Swagger document prior to starting the server but I don't know your server code so I'm not sure how you're starting things up.

**Comment by lazar725** [comment] 2016-04-06 19:44
Do you want me to send you the yaml file (just don't publish it anywhere)?

Lazar.

**Comment by whitlockjc** [comment] 2016-04-06 19:54
We can do that but there are two things you can tell me first that would render that unnecessary:

1. How did you validate your Swagger document?  _(What service, CLI tool, ... did you use?)_
2. Can you share the server code that wires up the swagger-tools' specific middlewares?

**Comment by lazar725** [comment] 2016-04-06 20:12
1. I used several tools to test the yaml, but here's one: 
http://yaml-online-parser.appspot.com/
2. I can share the entry point to the application, but I will send it to 
you tomorrow from my email at work, ok?

My email at work is lazar.gubezkis@pixoneye.com

Regards,
Lazar.

**Comment by whitlockjc** [comment] 2016-04-07 15:51
That is not enough.  YAML validation is not the same as Swagger validation.  You can run `swagger-tools validate YOUR_YAML` from the command line if you installed `swagger-tool` globally.  If you installed it locally, as in within your application, you could use `./node_modules/swagger-tools/bin/swagger-tools validate YOUR_YAML`.  But without seeing your application entry point, I can't ensure that this is even an issue because swagger-tools _(when used properly)_ will validate your Swagger document and refuse to start the server if the document is invalid.

As for sharing your entry point, you can copy/paste only the pertinent parts here and not worry about sharing any IP or secrets.  It shouldn't be hard.

**Comment by lazar725** [comment] 2016-04-10 11:57
This is the code that bootstraps the application:

`'use strict';

var express = require('express');
var app = express();
var swaggerTools = require('swagger-tools');
var jsyaml = require('js-yaml');
var fs = require('fs');
var cors = require('cors');
var serverPort = process.env.PORT || 8080;

// swaggerRouter configuration
var options = {
  swaggerUi: '/swagger.json',
  controllers: './controllers',
  useStubs: process.env.NODE_ENV === 'development' ? true : false // Conditionally turn on stubs (mock mode)
};

// The Swagger document (require it, build it programmatically, fetch it from a URL, ...)
var spec = fs.readFileSync('./api/swagger.yaml', 'utf8');
var swaggerDoc = jsyaml.safeLoad(spec);


// Initialize the Swagger middleware
swaggerTools.initializeMiddleware(swaggerDoc, function (middleware) {
  // Set CORS
  app.use(cors());

  // Interpret Swagger resources and attach metadata to request - must be first in swagger-tools middleware chain
  app.use(middleware.swaggerMetadata());

  // Validate Swagger requests
  app.use(middleware.swaggerValidator());

  // Route validated requests to appropriate controller
  app.use(middleware.swaggerRouter(options));

  // Serve the Swagger documents and Swagger UI
  app.use(middleware.swaggerUi());

  // Catch 404
  app.use(function (req, res, next) {
      res.status(404).json({ message: 'Path not found', status: 404 });
  });

  // Catch unhandled errors
  app.use(function (err, req, res, next) {
      res.status(500).json({ message: 'Unexpected error', status: 500, err: err });
  });

  /* Listen */
  app.listen(serverPort, function() {
      console.log('Your server is listening on port %d (http://localhost:%d)', serverPort, serverPort);
      console.log('Swagger-ui is available on http://localhost:%d/docs', serverPort);
  });
});
`

**Comment by whitlockjc** [comment] 2016-04-10 20:34
Looks fine because with this code, you've validating your Swagger so we know it's fine.  It seems swagger-ui has a bug in it.  I can update it during the next release but you can easily check to see if this is fixed already by following these steps:

* Download the latest swagger-ui using this link: https://github.com/swagger-api/swagger-ui/archive/master.zip
* Extract the zip file
* Update your server code to use `app.use(middleware.swaggerUi({swaggerUiDir: PATH_TO_SWAGGER_UI}));` where `PATH_TO_SWAGGER_UI` points to the `dist` directory within the location where you extracted swagger-ui
* Start your server
* Browse to the docs URL
* Put in the URL to your `/api-docs` into the browse form at the top of swagger-ui

If you run into the same problem, it seems the error is still not fixed on their end and you might want to file a bug with the steps to reproduce it.  If there is no error, close this issue and file a new one linking to this issue requesting an updated version of swagger-ui.

**Comment by whitlockjc** [comment] 2016-04-10 20:34
I didn't mean to close the issue, sorry.

**Comment by lazar725** [comment] 2016-04-11 07:04
Unfortunately, your solution didn't work. Now I have another problem: I extracted the zip file to my project and now I want to delete the swagger-ui folder, but it tells me that access is denied, despite the fact I'm running the cmd shell as administrator. I'm using Windows 10. How do I remove the folder?

**Comment by whitlockjc** [comment] 2016-04-11 15:55
I suggested no solution, just a series of steps to identify where the problem might be.  The steps were pretty clear but I'm open to hear where you got lost so we can get past it.  Long story short, swagger-tools' swagger-ui middleware ships with a binary distribution of [swagger-ui](https://github.com/swagger-api/swagger-ui) and that is what you see when you browse to `/docs`.  The error you're getting is within swagger-ui, not swagger-tools or its middleware and I'm trying to figure out if upgrading the swagger-ui binary in swagger-tools will fix your issue.  I outlined how to test this so where did you get stuck?

**Comment by lazar725** [comment] 2016-04-11 20:06
I didn't get stuck, I followed your series of steps, the app loaded but the bug was still there.

**Comment by whitlockjc** [comment] 2016-04-11 20:11
Okay, so this is a swagger-ui bug and unrelated to swagger-tools _(from what I can tell)_.  You will need to file a bug with swagger-ui, if one is not already created, with a reproduction recipe.  I'm closing this for now but feel free to reopen if you find that the issue is in fact with swagger-tools.

**Closed by whitlockjc** 2016-04-11 20:11 UTC
