### ISSUE TITLE
Allow external configuration of json body parser

### ISSUE THREAD

**Issue by mvaldesdeleon** [apigee-127/swagger-tools#454] opened 2016-11-24 11:14 UTC
The _swagger-metadata_ middleware uses **body-parser** to parse JSON payloads.

The actual json parser is instantiated on line 42:
```var jsonBodyParser = bp.json();```

However, this is using the default options for **body-parser**'s JSON parser (see doc [here](https://github.com/expressjs/body-parser#bodyparserjsonoptions)).

In my specific use-case, I am working with large JSON payloads, making me hit the default 100kb limit enforced by **body-parser**.

At this moment, I am forced to fork the project in order to customize the parser as needed.

I am not sure if there has already been considered a way to allow external configuration of the parsers. If this is the case, then I'd be glad to contribute a PR for this topic.

**Comment by whitlockjc** [comment] 2016-11-24 15:44
You are not forced to fork the project, you just need to provide the middleware yourself.  The middlewares we included are conditionally activated based on necessity.  So if you need a custom version, or a custom configuration, just wire them up as you would otherwise and your version will be used.  This is documented in the middleware documentation and has been discussed on numerous occasions.

Duplicate of #263 and #322 and others.

**Closed by whitlockjc** 2016-11-24 15:44 UTC
