### ISSUE TITLE
swaggerValidator: validate only the response

### ISSUE THREAD

**Issue by raphodn** [apigee-127/swagger-tools#534] opened 2017-09-28 05:34 UTC
Hello,

I wanted to know if it was possible to use swaggerValidator to only validate the reponses (i.e. `validateRequest: false`). After reading the docs and https://github.com/apigee-127/swagger-tools/issues/132 I seem to understand that it is not possible right ?

We are using swagger-tools to stub our apps backends during Automation Testing, and we would like to add configuration to turn on or off request AND/OR response validation.

We would also like to implement the possibility to turn on or off request AND/OR response validation at a path/method level.

Thanks anyway :)

**Comment by whitlockjc** [comment] 2017-09-28 16:05
Duplicate of #132.

**Closed by whitlockjc** 2017-09-28 16:05 UTC
