### ISSUE TITLE
Can't validate Swagger specs with external references to local files

### ISSUE THREAD

**Issue by IvanGoncharov** [apigee-127/swagger-tools#266] opened 2015-08-13 14:12 UTC
Can't validate following [example](https://github.com/swagger-api/swagger-spec/blob/master/examples/v2.0/json/petstore-separate/spec/swagger.json)
Because `swagger-tools` doesn't handle such [references](https://github.com/swagger-api/swagger-spec/blob/master/examples/v2.0/json/petstore-separate/spec/swagger.json#L139)

**Comment by whitlockjc** [comment] 2015-08-13 14:19
Duplicate of #227.

**Closed by whitlockjc** 2015-08-13 14:19 UTC
