### ISSUE TITLE
Swagger not picking up controllers inside as sub folder

### ISSUE THREAD

**Issue by atulatgithub** [apigee-127/swagger-tools#398] opened 2016-06-15 16:40 UTC
Hello,
I have configured to refer to controllers folder.
Inside controllers I have sub-folder which contains other controllers.
However, swagger is not picking up controllers.

@earth2marsh 
@bachp

**Comment by whitlockjc** [comment] 2016-06-15 16:46
This is a duplicate of #283.

**Closed by whitlockjc** 2016-06-15 16:46 UTC
