### ISSUE TITLE
`validate` doesn't fully validate relative references

### ISSUE THREAD

**Issue by janslow** [apigee-127/swagger-tools#381] opened 2016-05-17 13:33 UTC
If you have the following `swagger.yml` file, you (correctly) get an API error

```yaml
# swagger.yml
swagger: "2.0"
info:
  title: Foo
  version: "0.1"
paths:
  /bar:
    get:
      summary: Foo
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/FooModel"
definitions:
  FooModel:
    type: invalid-primitive
```

However, if you extract the definitions, it won't raise the issue:

```yaml
# swagger.yml
swagger: "2.0"
info:
  title: Foo
  version: "0.1"
paths:
  /bar:
    get:
      summary: Foo
      responses:
        200:
          description: OK
          schema:
            $ref: "model.yml#/definitions/FooModel"

# model.yml
definitions:
  FooModel:
    type: invalid-primitive
```

It does check that the ref is valid (i.e., the target exists) it just doesn't validate the contents of the file.

**Comment by whitlockjc** [comment] 2016-05-17 15:14
This is a duplicate of #227.

**Closed by whitlockjc** 2016-05-17 15:14 UTC
