### ISSUE TITLE
It marks response type of `file` invalid, incorrectly

### ISSUE THREAD

**Issue by nickretallack** [apigee-127/swagger-tools#174] opened 2015-03-03 00:40 UTC
This doesn't validate:

```yaml
swagger: '2.0'
info:
  version: "0.0.0"
  title: Example
paths:
  /test:
    get:
      responses:
        200:
          description: OK
          schema:
            type: file
```

[But it should](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#response-object).

This was reported on the Spec repo first: https://github.com/swagger-api/swagger-spec/issues/260

**Comment by whitlockjc** [comment] 2015-03-03 01:39
Here is what I get when I validate than YAML:

```
swagger-tools validate testing.yaml

API Errors:

  #/paths/~1test/get/responses/200: Data does not match any schemas from 'oneOf'
    #/paths/~1test/get/responses/200/schema/type: Data does not match any schemas from 'anyOf'
      #/schema/type: No enum match for: file
      #/schema/type: Expected type array but found type string
    #/paths/~1test/get/responses/200: Additional properties not allowed: schema,description

1 error and 0 warnings
```

It seems you cannot have a `type` of `file` based on the [schema.json#L948](https://github.com/swagger-api/swagger-spec/blob/master/schemas/v2.0/schema.json#L948), which references these: http://json-schema.org/latest/json-schema-core.html#anchor8  So based on the current JSON Schema file for Swagger, swagger-tools is validating as expected.

**Comment by nickretallack** [comment] 2015-03-03 01:41
The ```file``` type is not part of JSON Schema.  It is added by Swagger.

**Comment by whitlockjc** [comment] 2015-03-03 01:45
But the JSON Schema, the source of truth for doing schema validation, disallows it.  I linked to the location where this is enforced, I'm not making it up.

**Comment by whitlockjc** [comment] 2015-03-03 01:49
In fact, it's even acknowledged [upstream](https://github.com/swagger-api/swagger-spec/issues/260#issuecomment-72537952).

**Comment by nickretallack** [comment] 2015-03-03 01:49
I don't know why you're arguing with me about this.  It explicitly says in the swagger spec that this is supposed to be valid.

**Comment by nickretallack** [comment] 2015-03-03 01:50
Oh.  I guess you're saying this is an error in the JSON Schema that swagger uses to validate swagger schemas.  I was confused.  Well I guess they really do have to fix it in the spec, huh...

**Comment by whitlockjc** [comment] 2015-03-03 01:53
This is not an argument, I am pointing out facts.  The Swagger project has two parts: The [Swagger Specification](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md) and the [JSON Schema](https://github.com/swagger-api/swagger-spec/blob/master/schemas/v2.0/schema.json) that should validate documents to ensure they adhere to the specification where possible.  It seems there is a known bug, which I linked to, in the JSON Schema for Swagger 2.0 that disallows the use of `file` for a `schema` object's `type` property.  I've pointed to all of the relevant places that back me up so please don't think of this as an argument, I'm just trying to explain without ambiguity what is going on here and it is not a problem in this project.  Unfortunately, swagger-tools adheres to the JSON Schema for Swagger 2.0 and if it's busted, it is just the messenger for the errors that come about.

**Comment by nickretallack** [comment] 2015-03-03 01:54
Sorry.  Swagger is broken up into so many repositories that I'm having a really hard time figuring out where to file issues on things.  Every time I file an issue someone tells me it should be somewhere else :P

**Comment by whitlockjc** [comment] 2015-03-03 01:56
I understand your pain.  I'm sorry for the confusion and I hope I didn't come off as a jerk.  I was trying to explain things clearly so there was no misunderstanding.

All of this being said, if you're in agreement that this is in fact caused by swagger-api/swagger-spec#260, feel free to close this.  I'll leave it open just in case you want to chat more.

**Closed** 2015-03-03 01:57 UTC

**Comment by whitlockjc** [comment] 2015-03-03 01:58
Also, if you ever run into issues with projects that use swagger-tools, I don't mind you filing the bug here.  I will help you track down the culprit and get you pointed in the right direction in the event it isn't swagger-tools.  :)
