### ISSUE TITLE
Swagger-tools 0.10.2 breaks TypeScript projects

### ISSUE THREAD

**Issue by zelein** [apigee-127/swagger-tools#539] opened 2017-10-12 20:45 UTC
I updated to the newest swagger-tools, and now the node process crashes on start.

```
import * as express from "express";
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at E:\git\ts_template\node_modules\swagger-tools\middleware\swagger-router.js:93:24
    at arrayEach (E:\git\ts_template\node_modules\lodash\lodash.js:537:11)
    at Function.forEach (E:\git\ts_template\node_modules\lodash\lodash.js:9359:14)
    at recursiveFileList (E:\git\ts_template\node_modules\swagger-tools\middleware\swagger-router.js:79:7)
    at arrayEach (E:\git\ts_template\node_modules\lodash\lodash.js:537:11)
    at Function.forEach (E:\git\ts_template\node_modules\lodash\lodash.js:9359:14)
    at handlerCacheFromDir (E:\git\ts_template\node_modules\swagger-tools\middleware\swagger-router.js:129:5)
```

It looks like [this commit](https://github.com/apigee-127/swagger-tools/commit/ca7ac0447ea00e2690358d5e02b4677b09736f6a) updated the regex to look for TypeScript files, but it is not treating them any differently than JS files?

**Comment by whitlockjc** [comment] 2017-10-12 23:57
Maybe @rjnienaber can chime in.

**Comment by rjnienaber** [comment] 2017-10-14 16:57
@zelein is it possible to add some more info on how to reproduce the error? I created a hello-world app with swagger-tools and it seems to still work:

**Create new swagger project**
```
$ npm install -g swagger
$ swagger project create hello-world
? Framework? express
Project hello-world created in /home/richard
hello-world
Running "npm install"...
npm
 notice created a lockfile as package-lock.json. You should commit this file.

added 228 packages in 3.959s

Success! You may start your new app by running: "swagger project start hello-world"
```
**Upgrade swagger-tools**
```
$ cd hello-world/
$ swagger project start .
$ yarn add swagger-tools
$ grep version node_modules/swagger-tools/package.json 
 "version": "0.10.3",
```

**Run project**
```
$ swagger project start .
Starting: /home/richard/hello-world/app.js...
  project started here: http://localhost:10010/
  project will restart on changes.
  to restart at any time, enter `rs`
try this:
curl http://127.0.0.1:10010/hello?name=Scott

$ curl http://127.0.0.1:10010/hello?name=Scott
"Hello, Scott!"
```

**Comment by rjnienaber** [comment] 2017-10-14 21:35
You can then convert the above to a working Typescript project by doing the following:

**Add Typescript**
```
$ yarn add typescript ts-node @types/node
$ rm -r node_modules/swagger-express-mw/node_modules/swagger-tools/
$ find -name "*.js" -not -path "./node_modules/*" -exec rename 's/\.js$/.ts/' '{}' \;

# this is required as some extra validation seems to happen during the response
$ sed -i -e "s/  var hello =/  var message =/g" api/controllers/hello_world.ts 
$ sed -i -e "s/res.json(hello)/res.json({message})/g" api/controllers/hello_world.ts 
```

**Run project**
```
$ ./node_modules/ts-node/dist/bin.js app.ts
try this:
curl http://127.0.0.1:10010/hello?name=Scott

$ curl -s http://127.0.0.1:10010/hello?name=Scott
{"message":"Hello, Scott!"}
```

**Comment by whitlockjc** [comment] 2017-10-14 22:37
I'm going to close this since it seems like it's a usage issue and not a bug.  Feel free to continue the conversation.

**Closed by whitlockjc** 2017-10-14 22:37 UTC

**Comment by zelein** [comment] 2017-10-16 15:21
Okay, so I've done some investigation this morning and I have some results.

In the `swagger-router.js` file, the logic for resolving handlers was changed in the `handlerCacheFromDir` function to no longer resolve files with their extensions.

The logic in that function in `0.10.2` iterates over each file in the folder and resolves it using `require`. This is a problem for normal TypeScript projects because obviously `require` does not understand .ts extensions. 
This is not showcased in your example above because you are using `ts-node`, which augments `require` to understand .ts file types.

For the `0.10.3` release, the logic in that method changed slightly. It still iterates over each file in the directory, but for each file that matches the regular expression, it is resolved without the extension. So now it is effectively resolving everything twice as often as it needs to. This is assuming that the project is configured to output the JavaScript in the same folder as the TypeScript files.

So continuing using the example above, but assuming a normal TypeScript project that does not use ts-node, the `hello-world/api/controllers` folder would contain two files:

* `hello_world.ts`
* `hello_world.js`

The logic in `0.10.3` will iterate over both files, but will require them as `hello_world`, resolving the javascript file twice.

The logic in `0.10.2` will iterate over both files, but will require them as `hello_world.js` and `hello_world.ts`, blowing up when it tries to require .ts.

So the bug still exists, it's just been masked by how the controller is resolved. The change that "fixed" this was in commit [19874a1](https://github.com/apigee-127/swagger-tools/commit/19874a1f5d900f91e046840434392b799ce8e2d1)

**Comment by whitlockjc** [comment] 2017-10-16 15:36
The referenced commit was there to undo the support for nested controllers, a feature that should go in a minor/major semver and not a patch.  Actually, what changed TypeScript loading logic was ca7ac0447ea00e2690358d5e02b4677b09736f6a, which was an attempt to _support TypeScript_.  I think the issue is when you have your `.ts` files compiling to `.js` files in the same source directory, things will work as you describe above.  This would likely happen with `.coffee` files as well.

Not using TypeScript myself, I don't know what convention is for doing this but I never put src and generated files in the same directory, nor do I ship tests and sources in the same directory.  The commit you referenced shouldn't alter the `pre-0.10.2` loading of controllers and the way it worked in `0.10.2` was accidental.  So instead of comparing what's happening now to `0.10.2`, let's discuss how it _should_ work.  _(I think #354 will likely be involved in the answer.)_

**Comment by zelein** [comment] 2017-10-16 21:06
The location of the TS files is irrelevant as far as TS support goes for this library. The TS support that currently exists in swagger-tools (or at least what existed in `0.10.2`) is misleading. Support for `ts-node` was added, but in the process of adding support, broke TypeScript projects that happen to compile their js files in the same location as their ts files.

To properly support native TS files, the TypeScript API or the `ts-node api` would need to be used to process the .ts files as they come in at runtime.

**Comment by whitlockjc** [comment] 2017-10-16 21:15
Well, the location is relevant in the event that there are multiple files with the same name but different extensions in the same directory, and each of them are valid extensions.  So if a `hello_world.js` and `hello_world.ts` exist in the same controllers directory, both would attempt to be loaded.

It seems like there needs to be a way to tell which extension you're interested in loading because right now, there is an array _(`coffee`, `js`, `ts`)_ of permissible extensions that could be loaded.

**Comment by zelein** [comment] 2017-10-16 21:38
Seems like the executing method could execute the relevant loader as it encounters the file extensions it supports.

- *.js - require()
- *.ts - TS API (or potentially require() depending on if ts-node were used)
- *.coffee - ?? (I've never used CoffeeScript)

**Comment by zelein** [comment] 2017-10-16 21:39
But then you still have the case where they all exist in the same folder (like you were saying.)
