### ISSUE TITLE
How to remove/replace the swagger icon on the top left corner

### ISSUE THREAD

**Issue by Ckim15** [apigee-127/swagger-tools#210] opened 2015-05-07 00:17 UTC
Hi,

Is there any way that I can change the logo to my favorite one (attached image)? Also I need to customize the green background of that logo. I am cur
![swagger logo](https://cloud.githubusercontent.com/assets/10535043/7506367/8b76fb44-f424-11e4-9bfb-feb51f0bcc87.png)
rently using swagger-tools.

**Comment by whitlockjc** [comment] 2015-05-07 02:35
Altering the provided swagger-ui distribution isn't advised but you can download your own, theme it and the pass the proper option to the swagger-ui middleware to serve tour custom swagger-ui distribution.  That's how I'd do it.  Just know that the provided distribution has a customization to index.html to get the API URL from swagger-tools.  I can help with that.

Since this is not a bug, I'm going to close this but feel free to keep discussing this here and I'll help you get it sorted.

**Closed by whitlockjc** 2015-05-07 02:35 UTC

**Comment by aline-matos** [comment] 2017-04-07 14:55
Hi @whitlockjc! How can I use my own custom index.html? Thanks in advance

**Comment by whitlockjc** [comment] 2017-04-07 14:56
Use `options.swaggerUiDir` as documented here: https://github.com/apigee-127/swagger-tools/blob/master/docs/Middleware.md#swaggeruioptions

**Comment by amirhosseinmanian** [comment] 2017-11-16 04:55
just add this at the end of "window.onload" function:
document.getElementsByClassName('topbar-wrapper')[0].getElementsByTagName('img')[0].src = "myimage.png";
