### ISSUE TITLE
spec.validate gives warnings for unused definitions when using inheritance. spec.validateModel does not detect those definitions and gives no errors when validating invalid objects.

### ISSUE THREAD

**Issue by nhhagen** [apigee-127/swagger-tools#196] opened 2015-04-17 13:12 UTC
Given the spec:

```yml
swagger: '2.0'
info:
  version: 0.9.8
  title: test
  description: test
  termsOfService: test
  contact:
    name: test
    email: test@test.com
    url: http://www.test.com
  license:
    name: test
    url: http://www.test.com
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /api/test:
    post:
      tags: [test]
      operationId: test
      parameters:
        - name: body
          in: body
          description: test
          required: true
          schema:
            $ref: '#/definitions/testRequest'
      responses:
        200:
          description: test
          schema:
            $ref: '#/definitions/testResponse'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'

definitions:
  testRequest:
    discriminator: type
    properties:
      a_string:
        type: string
      type:
        type: string
    required:
      - type

  testRequest2:
    allOf:
    - $ref: '#/definitions/testRequest'
    - properties:
        another_string:
          type: string
          enum: [a, b, c]
      required:
          - another_string

  testResponse:
    properties:
      a_string:
        type: string

  errorModel:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
```

`spec.validate` gives a result with this warning:

```javascript
[ { code: 'UNUSED_DEFINITION',
      message: 'Definition is defined but is not used: #/definitions/testRequest2',
      path: [ 'definitions', 'not' ] }]
```

I find that strange. When passing an invalid `testRequest2`object to `spec.validataModel` you get no errors.

```javascript
{
  type: 'testRequest2`,
  a_string: 'sdfsdf',
  another_string: 'x'
}
```

**Comment by whitlockjc** [comment] 2015-04-17 13:51
This is a duplicate of #187.

**Closed by whitlockjc** 2015-04-17 13:51 UTC
